const PRESCRIPTION_DRUGS = new Set([
  // Antibiotics
  "amoxicillin",
  "augmentin",
  "azithromycin",
  "zithromax",
  "ciprofloxacin",
  "cipro",
  "doxycycline",
  "metronidazole",
  "flagyl",
  "clindamycin",
  "trimethoprim",
  "sulfamethoxazole",
  "bactrim",
  "levofloxacin",
  "levaquin",
  "ampicillin",
  "penicillin",
  "tetracycline",
  "vancomycin",
  "cephalexin",
  "keflex",
  "cefdinir",
  "omnicef",
  "nitrofurantoin",
  "macrobid",
  "linezolid",

  // Antidepressants / SSRI / SNRI
  "fluoxetine",
  "prozac",
  "sertraline",
  "zoloft",
  "escitalopram",
  "lexapro",
  "citalopram",
  "celexa",
  "paroxetine",
  "paxil",
  "venlafaxine",
  "effexor",
  "duloxetine",
  "cymbalta",
  "bupropion",
  "wellbutrin",
  "mirtazapine",
  "remeron",
  "fluvoxamine",
  "luvox",
  "desvenlafaxine",
  "pristiq",
  "nortriptyline",
  "amitriptyline",
  "elavil",
  "imipramine",
  "tofranil",

  // Antipsychotics
  "quetiapine",
  "seroquel",
  "aripiprazole",
  "abilify",
  "olanzapine",
  "zyprexa",
  "risperidone",
  "risperdal",
  "haloperidol",
  "haldol",
  "clozapine",
  "clozaril",
  "ziprasidone",
  "geodon",
  "lurasidone",
  "latuda",
  "paliperidone",
  "invega",

  // Benzodiazepines / sedatives
  "alprazolam",
  "xanax",
  "clonazepam",
  "klonopin",
  "diazepam",
  "valium",
  "lorazepam",
  "ativan",
  "temazepam",
  "restoril",
  "midazolam",
  "versed",
  "triazolam",
  "halcion",
  "zolpidem",
  "ambien",
  "eszopiclone",
  "lunesta",

  // Opioids / pain
  "oxycodone",
  "oxycontin",
  "percocet",
  "hydrocodone",
  "vicodin",
  "norco",
  "codeine",
  "tramadol",
  "ultram",
  "morphine",
  "fentanyl",
  "buprenorphine",
  "suboxone",
  "methadone",
  "hydromorphone",
  "dilaudid",
  "tapentadol",
  "nucynta",

  // Cardiovascular
  "lisinopril",
  "atenolol",
  "metoprolol",
  "lopressor",
  "amlodipine",
  "norvasc",
  "carvedilol",
  "coreg",
  "losartan",
  "cozaar",
  "valsartan",
  "diovan",
  "ramipril",
  "altace",
  "enalapril",
  "furosemide",
  "lasix",
  "spironolactone",
  "aldactone",
  "hydrochlorothiazide",
  "hctz",
  "warfarin",
  "coumadin",
  "apixaban",
  "eliquis",
  "rivaroxaban",
  "xarelto",
  "clopidogrel",
  "plavix",
  "digoxin",
  "amiodarone",
  "cordarone",
  "diltiazem",
  "verapamil",

  // Statins / lipid-lowering
  "atorvastatin",
  "lipitor",
  "rosuvastatin",
  "crestor",
  "simvastatin",
  "zocor",
  "pravastatin",
  "pravachol",
  "lovastatin",
  "mevacor",
  "ezetimibe",
  "zetia",
  "fenofibrate",
  "tricor",

  // Diabetes
  "metformin",
  "glucophage",
  "insulin",
  "glipizide",
  "glucotrol",
  "glimepiride",
  "amaryl",
  "glyburide",
  "sitagliptin",
  "januvia",
  "liraglutide",
  "victoza",
  "semaglutide",
  "ozempic",
  "wegovy",
  "empagliflozin",
  "jardiance",
  "canagliflozin",
  "invokana",
  "pioglitazone",
  "actos",

  // Thyroid
  "levothyroxine",
  "synthroid",
  "liothyronine",
  "cytomel",
  "methimazole",
  "tapazole",
  "propylthiouracil",
  "ptu",

  // Asthma / respiratory
  "albuterol",
  "proair",
  "ventolin",
  "salmeterol",
  "fluticasone",
  "flovent",
  "advair",
  "montelukast",
  "singulair",
  "tiotropium",
  "spiriva",
  "budesonide",
  "pulmicort",
  "ipratropium",
  "atrovent",
  "omalizumab",

  // Steroids / immunosuppressants
  "prednisone",
  "prednisolone",
  "methylprednisolone",
  "medrol",
  "dexamethasone",
  "hydrocortisone",
  "cortisone",
  "betamethasone",
  "methotrexate",
  "azathioprine",
  "imuran",
  "cyclosporine",
  "tacrolimus",
  "mycophenolate",
  "cellcept",
  "hydroxychloroquine",
  "plaquenil",

  // Antivirals
  "acyclovir",
  "zovirax",
  "valacyclovir",
  "valtrex",
  "oseltamivir",
  "tamiflu",
  "ritonavir",
  "lopinavir",
  "efavirenz",
  "atazanavir",
  "tenofovir",
  "emtricitabine",
  "truvada",

  // Antifungals
  "fluconazole",
  "diflucan",
  "itraconazole",
  "sporanox",
  "voriconazole",
  "vfend",
  "ketoconazole",

  // Neurological
  "gabapentin",
  "neurontin",
  "pregabalin",
  "lyrica",
  "topiramate",
  "topamax",
  "lamotrigine",
  "lamictal",
  "levetiracetam",
  "keppra",
  "valproate",
  "valproic acid",
  "depakote",
  "carbamazepine",
  "tegretol",
  "phenytoin",
  "dilantin",
  "phenobarbital",
  "carbidopa",
  "levodopa",
  "sinemet",
  "ropinirole",
  "requip",
  "pramipexole",
  "mirapex",
  "donepezil",
  "aricept",
  "memantine",
  "namenda",
  "riluzole",
  "rilutek",

  // ADHD
  "methylphenidate",
  "ritalin",
  "concerta",
  "adderall",
  "amphetamine",
  "dexmethylphenidate",
  "focalin",
  "lisdexamfetamine",
  "vyvanse",
  "atomoxetine",
  "strattera",

  // Gastrointestinal (Rx)
  "omeprazole",
  "prilosec",
  "esomeprazole",
  "nexium",
  "pantoprazole",
  "protonix",
  "lansoprazole",
  "prevacid",
  "rabeprazole",
  "aciphex",
  "sucralfate",
  "carafate",
  "misoprostol",
  "cytotec",
  "mesalamine",
  "asacol",

  // Hormones / contraceptives (Rx)
  "estradiol",
  "progesterone",
  "testosterone",
  "finasteride",
  "propecia",
  "dutasteride",
  "avodart",
  "spironolactone",

  // Rheumatology / biologic
  "adalimumab",
  "humira",
  "etanercept",
  "enbrel",
  "infliximab",
  "remicade",
  "rituximab",
  "rituxan",
  "tofacitinib",
  "xeljanz",
  "abatacept",
  "orencia",

  // Anticoagulants / hematology
  "heparin",
  "enoxaparin",
  "lovenox",
  "dalteparin",
  "dabigatran",
  "pradaxa",
  "edoxaban",
  "savaysa",

  // Oncology (Rx)
  "tamoxifen",
  "nolvadex",
  "anastrozole",
  "arimidex",
  "letrozole",
  "femara",
  "imatinib",
  "gleevec",

  // Migraine
  "sumatriptan",
  "imitrex",
  "rizatriptan",
  "maxalt",
  "topiramate",
  "propranolol",
  "inderal",
  "amitriptyline",

  // Urological
  "tamsulosin",
  "flomax",
  "oxybutynin",
  "ditropan",
  "tolterodine",
  "detrol",
  "sildenafil",
  "viagra",
  "tadalafil",
  "cialis",
]);

export function isPrescriptionDrug(name: string): boolean {
  return PRESCRIPTION_DRUGS.has(name.toLowerCase().trim());
}
