import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-12">
      <Link
        href="/"
        className="mb-8 inline-block text-sm text-teal-400 hover:text-teal-300"
      >
        ← Back to Home
      </Link>

      <div className="mb-8 flex flex-col gap-1">
        <h1 className="text-4xl font-bold tracking-tight">Terms of Service</h1>
        <p className="text-sm text-muted-foreground">
          Last updated: April 2026
        </p>
      </div>

      <div className="flex flex-col gap-10 leading-relaxed text-slate-300">
        <Section title="1. Acceptance of Terms">
          <p>
            By accessing or using ToxiClear AI (&ldquo;the Service&rdquo;), you
            agree to be bound by these Terms of Service. If you do not agree, do
            not use the Service. These terms apply to all users including free
            and premium account holders.
          </p>
        </Section>

        <Section title="2. Description of Service">
          <p>
            ToxiClear AI is an educational drug interaction checker that uses AI
            and publicly available medical databases to provide information
            about potential interactions between medications and substances. The
            Service operates in two modes:
          </p>
          <BulletList
            items={[
              "Free tier: OTC medication and alcohol interactions",
              "Premium tier: prescription drugs, supplements, personalized health context, and curriculum-aligned educational content",
            ]}
          />
        </Section>

        <Section title="3. Medical Disclaimer">
          <p className="font-semibold uppercase tracking-wide text-slate-200">
            ToxiClear AI is not a medical service and does not provide medical
            advice.
          </p>
          <p>
            All content generated by ToxiClear AI is for educational and
            informational purposes only. It is not a substitute for professional
            medical advice, diagnosis, or treatment.
          </p>
          <p>
            Never make medical decisions based solely on information from
            ToxiClear AI. Always consult a qualified healthcare professional
            before changing, starting, or stopping any medication. In case of
            emergency, call 911 or your local emergency number immediately.
          </p>
        </Section>

        <Section title="4. Account Registration">
          <p>
            To access certain features you must create an account. You agree to:
          </p>
          <BulletList
            items={[
              "Provide accurate, current, and complete information",
              "Keep your password secure and confidential",
              "Notify us immediately of any unauthorized account access",
              "Be responsible for all activity under your account",
              "Not create accounts for others without their permission",
            ]}
          />
          <p>You must be at least 13 years old to create an account.</p>
        </Section>

        <Section title="5. Premium Access">
          <p>
            Premium access is available for a one-time payment of $15 USD. This
            grants lifetime access to Premium features as they exist at the time
            of purchase, plus future updates to those features.
          </p>
          <p>
            <span className="font-semibold text-slate-200">Refund policy:</span>{" "}
            Due to the nature of digital products, all sales are final. If you
            experience a technical issue preventing access to Premium features,
            contact us at{" "}
            <a
              href="mailto:toxiclearai@gmail.com"
              className="text-teal-400 underline underline-offset-2 hover:text-teal-300"
            >
              toxiclearai@gmail.com
            </a>{" "}
            and we will resolve it promptly.
          </p>
          <p>
            We reserve the right to modify, add, or remove Premium features over
            time. We will not remove core Premium features without reasonable
            notice to affected users.
          </p>
        </Section>

        <Section title="6. Acceptable Use">
          <p>You agree NOT to:</p>
          <BulletList
            items={[
              "Use ToxiClear AI to make clinical medical decisions for others",
              "Attempt to reverse engineer, scrape, or copy the Service",
              "Use automated tools to make bulk queries to the Service",
              "Attempt to circumvent premium access controls",
              "Impersonate another person or entity",
              "Use the Service for any illegal purpose",
              "Submit false health profile information intending to manipulate results for harmful purposes",
            ]}
          />
        </Section>

        <Section title="7. Intellectual Property">
          <p>
            All content, design, code, and AI-generated explanations produced by
            ToxiClear AI are owned by or licensed to ToxiClear AI. You may not
            reproduce, distribute, or create derivative works from any part of
            the Service without written permission.
          </p>
          <p>
            Drug database data sourced from OpenFDA and NIH RxNorm is in the
            public domain and used in accordance with their terms of use.
          </p>
        </Section>

        <Section title="8. Limitation of Liability">
          <p className="font-semibold uppercase tracking-wide text-slate-200">
            To the maximum extent permitted by law, ToxiClear AI and its
            creators shall not be liable for any indirect, incidental, special,
            or consequential damages arising from use of the Service, including
            but not limited to harm resulting from reliance on AI-generated drug
            interaction information.
          </p>
          <p>
            Your sole remedy for dissatisfaction with the Service is to stop
            using it and, if applicable, request a refund under Section 5.
          </p>
        </Section>

        <Section title="9. Privacy">
          <p>
            Your use of ToxiClear AI is also governed by our{" "}
            <Link
              href="/privacy"
              className="text-teal-400 underline underline-offset-2 hover:text-teal-300"
            >
              Privacy Policy
            </Link>
            , which is incorporated into these Terms by reference. Please review
            our Privacy Policy before using the Service.
          </p>
        </Section>

        <Section title="10. Modifications to Terms">
          <p>
            We reserve the right to modify these Terms at any time. We will
            notify registered users of material changes via email at least 14
            days before they take effect. Continued use after that date
            constitutes acceptance of the updated Terms.
          </p>
        </Section>

        <Section title="11. Governing Law">
          <p>
            These Terms are governed by the laws of the State of New Jersey,
            United States, without regard to conflict of law principles.
          </p>
        </Section>

        <Section title="12. Contact">
          <p>
            For questions about these Terms, contact us at:{" "}
            <a
              href="mailto:toxiclearai@gmail.com"
              className="text-teal-400 underline underline-offset-2 hover:text-teal-300"
            >
              toxiclearai@gmail.com
            </a>
          </p>
        </Section>
      </div>
    </main>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="flex flex-col gap-3">
      <h2 className="text-xl font-semibold text-slate-100">{title}</h2>
      {children}
    </section>
  );
}

function BulletList({ items }: { items: string[] }) {
  return (
    <ul className="flex flex-col gap-2 pl-1">
      {items.map((item) => (
        <li key={item} className="flex gap-2">
          <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-teal-500" />
          <span>{item}</span>
        </li>
      ))}
    </ul>
  );
}
